# Generated by Django 2.2 on 2021-07-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
